# Generated by Django 5.1.1 on 2025-06-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Getintouch_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('full_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Get In Touch Form Data',
                'verbose_name_plural': 'Get In Touch Form Data',
            },
        ),
        migrations.CreateModel(
            name='Landingpage_userdetails_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('full_name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=255)),
                ('no_of_users', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Long User Detail Form Data',
                'verbose_name_plural': 'Long User Detail Form Data',
            },
        ),
        migrations.CreateModel(
            name='small_userdetail_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('full_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('email_id', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('country_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Small User Detail Form Data',
                'verbose_name_plural': 'Small User Detail Form Data',
            },
        ),
    ]
